### ISSUE TITLE
Fix CGModel.get_bond_length_from_names

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/foldamers#12]
This function in cgmodel.py is broken - particle_2_type is not defined and there is no error handling. If we keep this function, should we add get by name for everything else?

**Comment by mrshirts** [comment]
Yeah, this looks like a stub function that was never used.  I don't see it used anywhere in cg_openmm or cg_foldamers.

I can imagine we might want this functionality eventually, but we probably will want to generalize it to multiple backbone and sidechain types, which means it will need to be reengineered anyway 

So we can probably delete it for now.  You want to do a PR to do that?

**Comment by cwalker7** [comment]
We got rid of this function. Closing.
