### ISSUE TITLE
Discussion of what sort of heteropolymer support we want

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/foldamers#25]
A couple thoughts for discussion on building heteropolymers- please chime in @tlfobe and @cwalker7 on your thoughts?

There's a moderate amount of heteropolymers support in the code right now.  There needs to be a little tweaking for it to run correctly, but it looks like it is possible to define a dictionary for each monomer, each with their own backbone backbone bond lengths, sigma and epsilons. and then have as many different monomers as one likes. 

Two things that it DOESN'T look like it it is supported right now is: 
 -  having different types of sidechain beads or backbone beads in the same monomer - i.e. one could have two beads in a sidechain (or a backbone), but they would have to have the same parameters.
 - bond constants, bond angle, and torsion angle parameters that depend on anything than whether the beads are backbone or sidechain.  So, a bb-bb-bb-sc torsion always has the same values, no matter how many different types of backbone beads there are in a monomer.

It would take a moderate amount more work to support such changes - so the question is whether it would be best to get it up and running as is, or to retool a lot more code and get it working. 

My instinct is to get working what's currently almost working, i.e. with the drawbacks identified above, and go with that, then work on expanding the bead potentials within particles, and generalizing the torsional potentials.  A lot of the stuff we would want to do in the near future (ABAB or ABCABC  heteropolymers with fixed backbone but and different sidechains) can be supported with this. 

Thoughts?

**Comment by mrshirts** [comment]
Comments @cwalker7, @tlfobe?

**Comment by cwalker7** [comment]
I think the multiple backbone bead types in one monomer is less an issue, since we could split it into multiple monomers. But I can see where we would want multiple side chain bead types, and be able to specify the connectivity - maybe even allowing for nonlinear side chains eventually.

I think we could start with the heteropolymers having 1 type of backbone bead / 1 type of sidechain bead within each monomer type. The angles and torsions shouldn't be that hard to generalize if we have the bond list - we'd mostly just need to update the get_bond_angle_list and get_torsion_list in the cgmodel code.

**Comment by tlfobe** [comment]
I'm also for getting what results we can get from this current model. As long as we can ask the scientific questions we want to get out in the first paper we should be okay. That being said, we should keep in mind what changes would be needed to add this missing functionality.

These details will have a pretty big impact on how we convert structures/energy functions from CGPyRosetta to CGOpenMM, so at least having an idea of how much input/output will change will be useful.

**Comment by mrshirts** [comment]
OK, I think that I can get the code with limitations up and running very quickly (like a couple of days).  

To get more control over the sidechains will involve having arbitrary bead types, instead of just sidchain and backbone beads.  This will make get_angle/get_torsion calls pretty easy.  The issue will be to build in topology for the beads, i.e. to say what the ordering and connectivity of the beads are within each monomer. That will be a bit hard to build the bond list for.  But we can cross that bridge when we get there.  I think that when specifying a monomer, if we just have a dictionary of bond lists within the topology, that will be sufficient to specify the topology - it's just getting that information out to the cg_model structure that may require some revamp.  I'll start a new issue on this once we have this part updated.

**Comment by mrshirts** [comment]
Here's my proposal for a more general heteropolymer build syntax.

We have a new type of data structure, particles, like so:

a = {"particle_name": "a", "mass": 72 amu, "sigma": 0.3 nm, "epsilon":0.1 kilojoule/mole }
b = {"particle_name": "b", "mass": 72 amu, "sigma": 0.4 nm, "epsilon":0.2 kilojoule/mole }
c = {"particle_name": "c", "mass": 72 amu, "sigma": 0.2 nm, "epsilon":0.3 kilojoule/mole }

# for all of the parameters below, the label is just a concatenation of the particle names.  

# This next line is optional: if "epsilons" is defined, then it overwrites the individual epsilons; but for parameter combinations it's not defined for, then standard combining rules are used (the combination rules used should become a setting of initializing the CG model)

epsilons = {"aa_eps": 0.1 kilojoule/mol, "ab_eps":0.2 kilojoule/mol,"bc_eps":0.5 kilojoule/mol}

# same for sigmas:

sigmas = {"aa_sigma": 0.1 nm, "bc_sigma":0.2 nm,"ac_sigma":0.3 nm}

# since with the number of particle types, there will be so many different possible bonded parameters, I propose implementing a default bond length / torsion periodicity, etc. that can be defined for the model (not just hard coded for all models).  Something like: 
bond_lengths = {
     "default_bond_length": 3.0 nm,
    "a_b_bond_length": 2.0 * nm,
    "b_c_bond_length": 2.0 * nm,
    "a_c_bond_length": 2.0 *nm,
}

bond_force_constants = {
     "default_bond_force_constant": 500 kilojoules/mol*nm^2,
}

torsion_force_constants = {
     "a_b_c_a_torsion_force_constant": 20 kilojoules/mol,
     "default_torsion_force_constant": 10 kilojoules/mol
}

Then monomers defined as:
A = {  # a weird triangular backbone, with 2-bead side chain
    "monomer_name": "A",
    "particle_sequence": [a,a,a,b,c],  
    "bond_list": [[0,1], [1,2],[0,2],[1,3],[3,4]]
    "start": 0,
    "end": 2,
}

B = {   # a 1-1 bead
    "monomer_name": "B",
    "particle_sequence": [b,c],  
    "bond_list": [[0,1]],
    "start": 0,
    "end": 0,
}

C = {   # a 1-2 bead
    "monomer_name": "C",
    "particle_sequence": [b,c,c],  
    "bond_list": [[0,1], [1,2]],
    "start": 0,
    "end": 0,
}

This allows arbitrary connectivity between the atoms in the monomer, and arbitrary particles.  The bond list for the polymer should be easy to construct, since one knows which atom in which monomer connects with each one.  The random builder will have to be revisited, though, to account for rings, but we probably won't experiment with those until an extended builder is ready anyway.  For now, probably worth doing a scan for rings, and failing the random builder.

The get force routines should be pretty easy to generalize, since we now just have more than 2 types, otherwise the labels are the same.

**Comment by mrshirts** [comment]
That was pretty bad formatting. Fixed.

**Comment by mrshirts** [comment]
OK, this is implemented in PR #37.  I think that resolves most of the concerns brought up here.
