### ISSUE TITLE
Update angle and torsion distribution calculators

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/foldamers#31]
There are some scripts for calculating angle and torsion distributions in examples/evaluating_parameter_distributions. We probably want to generalize these and turn into functions for angle and torsion calculators - very useful if we are going to test out different torsion functional forms.

**Comment by mrshirts** [comment]
I can take a brief look at see how much revision they would take.

**Comment by cwalker7** [comment]
The new angle functions for the general heteropolymer update were merged in #38 (they are now located in analyze_foldamers).
