### ISSUE TITLE
extra replica added in get_temperature_list

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/foldamers#32]
In some cases there is an extra temperature added to the temperature list created with get_temperature_list in foldamers/parameters/reweight.py. Looks like it's a rounding issue. For example, if I specify 24 replicas with min_temp = 50K, max_temp = 400K, the 24th replica is 399.999... and 25th is 437K.

**Comment by mrshirts** [comment]
Can you take a look at that one?

**Comment by cwalker7** [comment]
This issue was fixed in the clustering PR #22. However, there still may be rounding error - something to fix when we combine calc_temperature_spacing and get_temperature_list.
