### ISSUE TITLE
foldamers/foldamers.py causing problems?

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/foldamers#35]
So, the file foldamers/foldamers.py seems to be causing problems.  When it's present, and I try to import the CGModel class definition with `from foldamers.cg_model.cgmodel import CGModel`, then I get the error:
`ModuleNotFoundError: No module named 'foldamers.cg_model'; 'foldamers' is not a package`.
When I move the file out of the way, things function correctly.  @tlfobe , you added this file in #28 - any guesses as to what is happening?

**Comment by cwalker7** [comment]
Not quite sure what's happening with that, but I'd say we can just get rid of foldamers.py. I think that was automatically created by the cookiecutter when we entered 'foldamers' as 'first module name.'

**Comment by mrshirts** [comment]
> I think that was automatically created by the cookiecutter when we entered 'foldamers' as 'first module name.'

Ah, OK, it's probably there to be a stub for starting the code - but the code is already there.  @tlfobe should I go ahead and remove it?
