### ISSUE TITLE
Merging cg_openmm and foldamers (or, revising how it's merged)

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/foldamers#44]
With the dependencies between cg_openmm and foldamers, it seems like we may want to move a lot of the functionality into the same repository, and just have analysis code that could be run on both cg_openmm and cg_pyrosetta code in a separate analyze_foldamers repository.  What do people think of this?

**Comment by cwalker7** [comment]
Based on the discussion at the 7/30 foldamers subgroup meeting, we decided to move a lot of the current foldamers repo to cg_openmm, and put structural analysis functions into a new repo foldamers_analysis which we want to be able to take in pdb files from either cg_openmm or pyrosetta. Thermodynamic analysis functions will go to cg_openmm.

We need to decide what goes where - I've put together a preliminary list:

**Move to cg_openmm**

- [x] cg_model.cgmodel

- [x] parameters.optimize (uses cg_openmm energy minimization - we should revisit this module)
- [x] parameters.reweight (thermo calculations)
- [x] parameters.secondary_structure (expectation calculation)
- [x] utilities.util (random builder for cg_openmm models)
- [x] ensembles.ens_build (uses openmm to get energies - we should revisit all of the functions in this)
- [x] thermo.calc (heat capacity calculation)
- [x] structure_library (need to remake this)
- [x] examples/evaluating_free_energy
- [x] examples/evaluating_heat_capacity
- [x] examples/generate_random_structures
- [x] examples/generating_ensembles
- [x] examples/plotting
- [x] examples/varying_model_parameters

**Move to foldamers_analysis**
- [x] ensembles.cluster (get positions from cgmodel but can change this to be directly from pdb)
- [x] parameters.secondary_structure (helical parameter analysis, native contacts calculation)
- [x] parameters.angle_distributions (uses only cgmodel for now, would need angle/torsion finders to parse a pdb)
- [x] utilities.plot (goes with angle calculator)
- [ ] examples/evaluating_folding
- [ ] examples/evaluating_parameter_distributions (just angle and torsions right now)
- [ ] examples/modeling_helices

**Delete**
- [ ] cg_model.data (cookiecutter files we already have in cg_openmm)

A lot of the examples need updating, but I think we should get the repo splitting sorted out first. Let me know if you think any of these should be switched, hoping to get most of the moving done in one shot.

**Comment by mrshirts** [comment]
> parameters.secondary_structure (helical parameter analysis, native contacts calculation)

There are calculations for expectation values of contacts lists, and that require the energies - expectations are thermodynamic calculations.  However, determining which lists of contacts are native contacts should stay in analyze_foldamers.

**Comment by cwalker7** [comment]
Ok. Probably for the files which are needed by both I will just copy to both cg_openmm and the new foldamers_analysis repo, and then do the edits.

I think I figured out how to preserve the commit history, I transferred one directory over so far, largely following the article we talked about (https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b). It will just be a little tedious because you can't select multiple directories with 'git --filter-branch --subdirectory-filter'.

**Comment by cwalker7** [comment]
The cg_openmm/foldamers merge is complete, closing this issue.

I will make a separate issue for the split of functionality in secondary_structure.py - for now, anything native contacts is in cg_openmm, and anything helical fitting is in analyze_foldamers.
